#!/bin/sh
rsync -av u85590865@home633566534.1and1-data.host:~/sweetandco/api_v2 --include=.env --include=public/.htaccess --include=public/build --include=vendor --exclude-from=.gitignore --exclude=".*"
